update bazel installation

diff --git a/.github/workflows/python-publish-bind.yml b/.github/workflows/python-publish-bind.yml
--- a/.github/workflows/python-publish-bind.yml
+++ b/.github/workflows/python-publish-bind.yml
@@ -72,7 +72,10 @@ jobs:
       run: |
         curl -LO https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh
         chmod +x bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh
-        ./bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh --user
+        (echo "===== Bazel installation Attempt: 1 ====" && ./bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh --user) ||
+        (echo "===== Bazel installation Attempt: 2 ====" && ./bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh --user) ||
+        (echo "===== Bazel installation Attempt: 3 ====" && ./bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh --user) ||
+        (echo "===== Bazel installation Step Failed ====" && exit 1);
         export PATH="$PATH:$HOME/bin"
         rm bazel-${BAZEL_VERSION}-installer-${BAZEL_TARGET}-x86_64.sh
     - name: Install dependencies
